import { MigrationInterface, QueryRunner } from 'typeorm';
export class AddSaasCore1773139300000 implements MigrationInterface {
 name = 'AddSaasCore1773139300000';
 async up(q: QueryRunner): Promise<void> {
  await q.query('ALTER TABLE "users" ADD COLUMN "avatar_url" character varying');
  await q.query('ALTER TABLE "users" ADD COLUMN "deactivated_at" TIMESTAMP WITH TIME ZONE');
  await q.query('CREATE TABLE "auth_tokens" ("id" uuid NOT NULL, "user_id" uuid NOT NULL, "kind" character varying NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_auth_tokens" PRIMARY KEY ("id"), CONSTRAINT "UQ_auth_tokens_hash" UNIQUE ("token_hash"))');
  await q.query('CREATE INDEX "IDX_auth_tokens_user_kind" ON "auth_tokens" ("user_id", "kind")');
  await q.query('CREATE TABLE "refresh_sessions" ("id" uuid NOT NULL, "user_id" uuid NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "replaced_by_id" uuid, "user_agent" character varying, "ip_address" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_refresh_sessions" PRIMARY KEY ("id"), CONSTRAINT "UQ_refresh_sessions_hash" UNIQUE ("token_hash"))');
  await q.query('CREATE INDEX "IDX_refresh_sessions_user" ON "refresh_sessions" ("user_id")');
  await q.query('CREATE TABLE "oauth_states" ("id" uuid NOT NULL, "provider" character varying NOT NULL, "state_hash" character varying NOT NULL, "code_verifier" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_oauth_states" PRIMARY KEY ("id"), CONSTRAINT "UQ_oauth_states_hash" UNIQUE ("state_hash"))');
  await q.query('CREATE TABLE "organizations" ("id" uuid NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_organizations" PRIMARY KEY ("id"), CONSTRAINT "UQ_organizations_slug" UNIQUE ("slug"))');
  await q.query('CREATE TABLE "memberships" ("id" uuid NOT NULL, "organization_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" character varying NOT NULL DEFAULT \'member\', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_memberships" PRIMARY KEY ("id"), CONSTRAINT "UQ_memberships_org_user" UNIQUE ("organization_id", "user_id"))');
  await q.query('CREATE TABLE "invitations" ("id" uuid NOT NULL, "organization_id" uuid NOT NULL, "email" character varying NOT NULL, "role" character varying NOT NULL DEFAULT \'member\', "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "accepted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_invitations" PRIMARY KEY ("id"), CONSTRAINT "UQ_invitations_hash" UNIQUE ("token_hash"))');
  await q.query('CREATE TABLE "billing_customers" ("id" uuid NOT NULL, "organization_id" uuid NOT NULL, "provider" character varying NOT NULL, "provider_customer_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_billing_customers" PRIMARY KEY ("id"), CONSTRAINT "UQ_billing_customers_org" UNIQUE ("organization_id"), CONSTRAINT "UQ_billing_customers_provider" UNIQUE ("provider_customer_id"))');
  await q.query('CREATE TABLE "subscriptions" ("id" uuid NOT NULL, "organization_id" uuid NOT NULL, "plan" character varying NOT NULL DEFAULT \'free\', "status" character varying NOT NULL DEFAULT \'active\', "provider_subscription_id" character varying, "current_period_end" TIMESTAMP WITH TIME ZONE, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_subscriptions" PRIMARY KEY ("id"), CONSTRAINT "UQ_subscriptions_org" UNIQUE ("organization_id"), CONSTRAINT "UQ_subscriptions_provider" UNIQUE ("provider_subscription_id"))');
 }
 async down(q: QueryRunner): Promise<void> { await q.query('DROP TABLE "subscriptions"'); await q.query('DROP TABLE "billing_customers"'); await q.query('DROP TABLE "invitations"'); await q.query('DROP TABLE "memberships"'); await q.query('DROP TABLE "organizations"'); await q.query('DROP TABLE "oauth_states"'); await q.query('DROP TABLE "refresh_sessions"'); await q.query('DROP TABLE "auth_tokens"'); await q.query('ALTER TABLE "users" DROP COLUMN "deactivated_at"'); await q.query('ALTER TABLE "users" DROP COLUMN "avatar_url"'); }
}
